/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GdkFontPeer */

#ifndef _Included_gnu_java_awt_peer_gtk_GdkFontPeer
#define _Included_gnu_java_awt_peer_gtk_GdkFontPeer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: bundle */
/*
 * Class:     gnu_java_awt_peer_gtk_GdkFontPeer
 * Method:    initStaticState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GdkFontPeer_initStaticState
  (JNIEnv *, jclass);

/*
 * Class:     gnu_java_awt_peer_gtk_GdkFontPeer
 * Method:    initState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GdkFontPeer_initState
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_gtk_GdkFontPeer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GdkFontPeer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_gtk_GdkFontPeer
 * Method:    setFont
 * Signature: (Ljava/lang/String;IIZ)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GdkFontPeer_setFont
  (JNIEnv *, jobject, jstring, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
