#!/usr/bin/env bash
# contrib/clang-format/hg-clang-format - apply clang format to hg diff
#
# Copyright (C) 1996-2014
# CACAOVM - Verein zur Foerderung der freien virtuellen Maschine CACAO
#
# This file is part of CACAO.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

###
# Usage: hg-clang-format [REV]
###

set -u

HG=${HG:=hg}
CLANG_FORMAT_DIFF=${CLANG_FORMAT_DIFF:=clang-format-diff.py}
REV=${1:-.}

$HG diff -U0 -r $REV | $CLANG_FORMAT_DIFF -i -p1
