#!/bin/sh

VERBOSE=0
EXITCODE=0

if [ -z "$JAVA" ] ; then
	JAVA=../../../src/cacao/cacao
fi

if [ "$1" = "--verbose" ] ; then
	shift
	VERBOSE=1
fi

JASMIN_JAR=/usr/share/java/jasmin-sable.jar
JASMIN="$JAVA -cp $JASMIN_JAR jasmin.Main"

while [ -n "$1" ]
do
    TEST="$1"
    TESTBASENAME=$(basename "$TEST" .j)

    TESTOUT="TESTOUT"
    TESTEXPECT="TESTEXPECT"
    TESTLOG="TESTLOG"

    $JASMIN "$TEST" || exit 2
    $JAVA "$TESTBASENAME" >"$TESTOUT" || exit 2

    grep 'OUTPUT:' "$TEST" | sed 's,.*OUTPUT:\s*,,' >"$TESTEXPECT"

    if diff -u "$TESTEXPECT" "$TESTOUT" ; then
    	echo "PASS: $TEST"
    else
    	echo "FAIL: $TEST"
	EXITCODE=1
    fi

    if [ "$VERBOSE" -eq "1" ] ; then
	$JAVA -sia "$TESTBASENAME" >"$TESTLOG" || exit 2
	./show "$TESTLOG"
    fi

    shift
done

#rm -f "$TESTOUT" "$TESTEXPECT" "$TESTLOG"

exit $EXITCODE

